# The Python Programming: Numerical Python (NumPy)

**NumPy**: 파이썬에 있는 객체를 매트릭스화 한 후 매트릭스를 연산할 수 있게 하는 모듈

In [1]:
import numpy as np

In [3]:
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [4]:
x = np.array(mylist)
x

array([1, 2, 3])

In [5]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [6]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
m.shape

(2, 3)

In [8]:
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [10]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [11]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [12]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [16]:
np.array([1, 2, 3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [17]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
p1 = np.vstack([p, 2*p])
p1

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [20]:
p2 = np.hstack([p, 3*p])
p2

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

In [21]:
x, y

(array([1, 2, 3]), array([4, 5, 6]))

In [22]:
x+y

array([5, 7, 9])

In [23]:
x-y

array([-3, -3, -3])

In [24]:
x*y

array([ 4, 10, 18])

In [25]:
x.dot(y)

32

In [26]:
x/y

array([0.25, 0.4 , 0.5 ])

In [27]:
x**2

array([1, 4, 9], dtype=int32)

In [28]:
z = np.vstack([x, y])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
z.T            # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
z.shape

(2, 3)

In [31]:
z.T.shape

(3, 2)

In [32]:
z.dtype

dtype('int32')

In [33]:
z = z.astype('f')
z.dtype

dtype('float32')

In [34]:
z.min()

1.0

In [35]:
z.argmin()

0